apigee-internal/microgateway

cli/cmd.js
cli/lib/gateway.js
lib/agent-config.js
npm-shrinkwrap.json
package.json
tests-cluster/cluster.js

add cluster logging, cluster will now write one log file

Cluster logging

---

cli/cmd.js
cli/lib/gateway.js
cli/lib/verify.js
lib/agent-config.js
lib/gateway.js
lib/plugins.js
lib/server.js
npm-shrinkwrap.json
package.json
tests/agent.js
tests/default.yaml

add global run for edgemicro via npm i edgemicro -g

---

cli/lib/configure.js
cli/lib/token.js

Motivation was easier use of MGW with e2e environment. 
* can configure management URI from environment
* can configure auth URI from environment
* can configure base URI from environment

add default config env vars

---

cli/cmd.js

Updated edgemicro command with --version option to print current version of edgemicro.

Microgateway version info added to commander

---

cli/edgemicro

Just a small helpful addition to print the current microgateway version like we print the current node version.

Adds the current version of edgemicro to printed version info.

---

cli/lib/cert-lib.js

EM stores public and private keys in the vault. This PR will change it to use KVM. A second PR will be needed to change the KVM to Encrypted KVM.

update cert store to kvm

---

package.json

Version bump for deps and package itself.

---

README.md

Adding a contribution guide, and some other standard README members.

Contrib guide

---

cli/lib/cert-lib.js
cli/lib/gateway.js
npm-shrinkwrap.json
package.json
tests/agent.js
tests/cli.js
tests/env.js
tests/server/hello/hello.js

Initial testing fixes to work with new microgateway changes.
-- An api uri big fix in cert-lib
-- Began implementing non CPS cert-lib KVM api updates
-- Fix tests (need to wait until cluster fully spins up before starting tests)
ASSUMPTIONS
1. The config that is pulled down must include a proxy whose endpoint is `/edgemicro_hello'.  As an accompanying change to this PR, our Travis CI config will need to be updated as well.
TODO
-- poll cluster for status before starting tests instead of just waiting 10 seconds
-- re-inject counting into plugins for testing that the correct number of calls were made.

initial test fixing

---

npm-shrinkwrap.json
package.json

Need to update shrinkwrap. Give a tidy version number for CF support.

Updating shrinkwrap, and version

---

cli/lib/gateway.js

Fixing spelling error in reload message.

---

cli/cmd.js
cli/lib/configure.js
cli/lib/gateway.js
cli/lib/init.js
config/locations.js
tests/config.js
tests/default.yaml

Consider this a WIP. Solves https://github.com/apigee/microgateway-core/issues/42. 
No core additions needed, just need to update modules to account for command line flag when calculating paths.

Adding support for setting a custom config directory.

---

cli/lib/gateway.js
cli/lib/reload-cluster.js

Adding logging support that regressed after the zero downtime config was reloaded.

---

cli/cmd-private.js
cli/lib/private.js

Starting support for custom config file directory for private configuration command.

---

cli/cmd.js
cli/lib/cert-lib.js
cli/lib/configure.js
cli/lib/deploy-auth.js

WIP.
This progress is meant to allow for the configuration edgemicro using an oauth access token instead of username and password.

SAML integration start.

---

cli/lib/cert-lib.js

fixing Travis CI build failure #552 from pull request #132

---

app.js
cli/cmd.js
cli/lib/configure.js
cli/lib/deploy-auth.js
cli/lib/gateway.js
cli/lib/rotate-key.js
cli/lib/verify.js
forever.js

The "edgemicro reload" command did not support the "-c" flag to set a custom config directory. This fix will now allow it.

add config dir support for edgemicro reload

---

cli/lib/gateway.js

Exit status on error

---

kubernetes/README.md
kubernetes/docker/edgemicro/dockerrun.sh
kubernetes/docker/edgemicro/entrypoint.sh
kubernetes/edgemicroctl/samples/plugins/Dockerfile
kubernetes/edgemicroctl/samples/plugins/plugins/response-uppercase/index.js
kubernetes/edgemicroctl/samples/plugins/plugins/response-uppercase/package.json

Custom Plugin required -d parameter to be passed in entrypoint.sh . Made some docs changes to talk about custom plugin, scaling deploying, changing configuration, multiple configuration.

Custom Plugins and added lot of documentation

---

cli/cmd.js
cli/lib/cert-lib.js
cli/lib/gateway.js

- specify pluginDir through a configuration file or environment variable
- specify externally generated key and cert pair during configuration

external pluginDir and key/cert pairs

---

kubernetes/docker/edgemicro/Dockerfile
kubernetes/docker/edgemicro/README.md
kubernetes/docker/edgemicro/dockerrun.sh
kubernetes/docker/edgemicro/entrypoint.sh
kubernetes/docker/edgemicro/proxies.yaml
kubernetes/edgemicroctl/src/main.go

Changes to Dockerfile:
1. Move multiple  RUN operations to a single RUN operation
2. Set USER before entrypoint
3. mount volume for plugins
Changes to entrypoint.sh
1. Deprecate `EDGEMICRO_DOCKER`
Changes to edgemicroctl
1. Add Security Context to Deployment.
a. Set RunAsRoot to false
b. Set RunAsUser to apigee

Docker updates

---

kubernetes/edgemicroctl/install/kubernetes/edgemicro-sidecar-injector-configmap-release.yaml

Running as non root container

---

kubernetes/README.md
kubernetes/docker/edgemicro/Dockerfile
kubernetes/docker/edgemicro/README.md
kubernetes/docker/edgemicro/install.sh
kubernetes/docker/edgemicro_apigee_setup/Dockerfile
kubernetes/docker/edgemicro_proxy_init/Dockerfile

Fix typo in `chwon apigee:apigee /tmp/entrypoint.sh`
Move install scripts to install.sh

create install.sh; fix typo

---

cli/cmd-cert.js
cli/lib/cert.js
tests/cli-cert-oauth.integ.test.js
tests/env.js

edgemicro-cert -t token option

---

kubernetes/edgemicroctl/.goreleaser.yml

Some of the tests were not working before. But, they pass now.

I have forked this repository and am making changes to tests. 

---

cli/lib/reload-cluster.js

The event handlers messages are logged in files with logging level 'info'.

Log cluster events messages

---

.eslintrc
npm-shrinkwrap.json
package.json

As of now we are planning not to enable all the rules but do it step by step.

add eslint config

---

app.js
cli/cmd-cert.js
cli/cmd-private.js
cli/cmd-token.js
cli/cmd.js
cli/edgemicro
cli/lib/cert-lib.js
cli/lib/cert.js
cli/lib/configure.js
cli/lib/deploy-auth.js
cli/lib/gateway.js
cli/lib/init.js
cli/lib/key-gen.js
cli/lib/private.js
cli/lib/reload-cluster.js
cli/lib/rotate-key.js
cli/lib/start-agent.js
cli/lib/token.js
cli/lib/upgrade-edgeauth.js
cli/lib/upgrade-kvm.js
cli/lib/verify.js
cli/package.js
forever.js
lib/plugins.js
lib/server.js

Pass the component name to core function writeConsoleLog.

139064616 Console log standardization

---

test-functional/NightlyTests.sh
test-functional/testEMG.sh
test-functional/testhelper.sh

testLogFileCreated:
Checks if the log file is created.
testInvalidApiKeyEventLog:
Checks if invalid apikey is printed in log and also covers the event error log functionality.
testInfoLogs:
Checks if system info logs and event info logs are printed in log file.
Checks if no trace and debug logs are printed when level is info.
testDebugLogs:
Checks if system debug logs and event debug logs are printed in log file.
Checks if no trace logs are printed when level is debug.
testTraceEventLog:
Checks if event trace logs are printed in log file.

for306 Add test cases for logging functionalities

---

cli/lib/gateway.js
npm-shrinkwrap.json
package.json

Below is an example of yaml configuration:
edge_config:
synchronizerMode: 1
If set to 0, the EMG instance should work as is. Non Synchronizer mode.
If set to 1, the EMG instance should work only as a Synchronizer. This mode should not create any worker nodes.
Write responses of bootstrap, products and jwt_public_key to RedisDB at every config_change_poll_interval.

Fix bug 147579179 and implement synchronizerMode configuration

---

cli/lib/verify.js

Pass the org and env in option to build the correct quotaUri and redis key.
Append '/v2/quotas/apply' in quotaUri.

150746985 Fix issues in verify command

---

cli/lib/gateway.js
lib/server.js
npm-shrinkwrap.json
package.json
tests/heapdump_test.js

Capture both master and worker heapsnapshot if EMG_HEAPDUMP_MODE env variable is set and emg is running in development mode.
Set EMG_HEAPDUMP_PATH env variable to configure location for heapsnapshot.

Add support to capture heapdump in development mode

---

cli/cmd-private.js
cli/cmd.js
cli/lib/deploy-auth.js
cli/lib/upgrade-edgeauth.js

Add 'org.noncps' value to JavaCallout file
Add property 'org.noncps' and set to 'true', if edgemicro private upgradeauth is invoked
Remove property 'org.noncps' if edgemicro upgradeauth is invoked

For org noncps

---

lib/agent-config.js

Replace all occurances of a env variable to minimize iteration

156560067 Improve env replacement logic

---

cli/cmd-private.js
cli/cmd.js
cli/lib/rotate-key.js

Add below options in private and non private rotatekey cli command.
-n = nbf time in minutes
-p = Path to private key to be used by Apigee Edge
-c = Path to certificate to be used by Apigee Edge

Add new options in rotate key.

---

cli/lib/gateway.js
lib/plugins.js

Pass all the plugin dir names to gateway's plugin loaders.

160431789 Pass plugin dirs to plugin loader

---

npm-shrinkwrap.json
package.json

Upgrade forever-monitor to 3.0.1

Upgrade forever-monitor

---

cli/lib/gateway.js
lib/plugins.js

Pass all the plugin dir names to gateway's plugin loaders.

160431789 Pass plugin dirs names to plugin loader

---

cli/cmd-private.js
cli/cmd.js
cli/lib/rotate-key.js

Add below options in private and non private rotatekey cli command.
-n = nbf time in minutes
-p = Path to private key to be used by Apigee Edge
-c = Path to certificate to be used by Apigee Edge

b/154838259,163711992-Add new options in rotateKey.

---

cli/lib/verify.js

Fix verify command to work with quota plugin in redis mode.

158618994 Fix verify command issue

---

.travis.yml
cli/edgemicro
cli/lib/gateway.js
package.json

Add EMG support for node js 14.

Add EMG support for node js 14.

---

npm-shrinkwrap.json
package.json

Remove unused dependency 'run-sequence'
Update dependency 'gulp-shell'

180361669 Update dev dependencies

---

cli/lib/reload-cluster.js
test-stress/reload-cluster-old.js

Add prior notice to worker process before disconnect
Updated all the references of memored to emgCache

190715670 Fix the issue of requests getting stuck on reload

---

cli/lib/key-gen.js

Modified the code to use key and secret as credentials for
authenticating the revoke keys request

215748732 Fix revoke keys functionality

---

kubernetes/installer/README.md

Hi Imesh -- I made a few minor edits to the README to make sure I remember how to work in Git. After this is merged successfully, I'll probably make additional edits.

minor edits

---

kubernetes/docker/edgemicro/Dockerfile

modified code to make node 14 as default node for docker
images

221432797 Node 14 as default docker node

---

cli/cmd.js
cli/lib/key-gen.js

Optimised code to be able to support token authentication while
revoking key

215748732 Edgemicro revoke keys -t support

---

cli/lib/private.js

Optimized the code to find or create 'REGION_MAP' property in
Callout.xml and update the value with given runtimeUrl

231972608 Fix edgemicro private configure issue

---

cli/edgemicro
package.json

Add warning message for node js 10 version

220885293 Add node.js 16 support for microgateway
