cli/cmd.js, cli/lib/gateway.js, cli/lib/json-socket.js, cli/lib/reload-cluster.js, cli/lib/start-agent.js, config/default.yaml, config/locations.js, lib/agent-config.js
1. Introducing ability to reload microgateway for new config without dropping messages.
2. Reloading is done using IPC through sockets.
3. After this change, microgateway will always be starting in cluster mode.
4. Owing to this there are 3 new commands added. Status, Reload, Stop.
=> Zero Downtime reload config capability

cli/lib/gateway.js
The `-p` flag doesn't work as expected currently. This is a fix for that.
=> Need to be able to specify number of processes cluster should use with the -p or --processes flag.

.gitignore, cli/lib/cert-lib.js, cli/lib/cert.js, cli/lib/configure.js
This fixes issues when trying to configure EM with a custom URL.
=> Formatting the url before handing it off to the cert lib.

cli/lib/gateway.js, lib/agent-config.js
Currently we pass API keys to clustered edgemicro processes. This is not desirable because it exposes credentials to anyone that can inspect running processes.
This PR uses a cached config to lookup credentials in processes.
=> Updates to remove keys from process args.

cli/lib/gateway.js
Adds a config option under edgemicro. `config_disable_poll_interval` set to `true` it will disable the polling interval against edge looking for a new config. Currently defaults to `false`.
=> Add a configuration option to disable polling.

lib/server.js
PCF has issues with the zero downtime reload feature.
TL;DR
When PCF allows EM to execute a reload it doesn't pick up environment variables that it needs to run. Like port. This causes EM to be marked unhealthy and restart.
This fix accounts for that. @kenigeer As someone with more PCF experience are there other env variables I should account for and override in the config?
-Matt
=> Updating reload of config to use port env variable.

cli/lib/configure.js, config/locations.js
Right now the custom configuration directory depends on the existence of an `.edgemicro` directory to work. This remedies that.
=> Updating to not need an existing .edgemicro directory for config.

cli/cmd.js, cli/lib/configure.js
As a user I may change the name of my edgemicro-auth proxy. This fixes that.
=> Set a custom proxyName for edgemicro-auth proxy

cli/lib/cert-lib.js, cli/lib/configure.js, cli/lib/private.js
This commit resolves the following error when executing "edgemicro private configure"
{ code: 'keyvaluemap.service.keyvaluemap_already_exist', message: 'KeyValueMap microgateway already exists', contexts: [] }
I also changes some of the console log statements from "vault" to "KVM."
=> Resolves EM-199 - error when trying to execute "edgemicro private configure" command

kubernetes/README.md, kubernetes/docker/edgemicro/entrypoint.sh, kubernetes/docker/edgemicro_apigee_setup/setup.sh
These changes will help to scale pods created as edgemicro sidecar.
It will create a proxy with name edgemicro_service
and a product with name edgemicro_service-product
How to Test:
kubectl scale deployment helloworld --replicas=2
kubectlkubectl get pods
NAME READY STATUS RESTARTS AGE
helloworld-5bfcfb4d6f-l2kxd 2/2 Running 0 11m
helloworld-5bfcfb4d6f-rldw2 2/2 Running 0 15m
curl ingress-ip -H 'x-api-key: my-api-key'
Delete an old pod
kubectl delete pod helloworld-5bfcfb4d6f-rldw2
curl ingress-ip -H 'x-api-key: my-api-key'
=> Changing proxy name to reflect the service name

cli/cmd-private.js
Introduce debug option for Edgemicro private cloud. This
feature is needed to enable debug information.
=> Enable debug option for Edgemicro private cloud

app.js, cli/cmd-cert.js, cli/cmd-private.js, cli/cmd-token.js, cli/cmd.js, cli/edgemicro, cli/lib/cert-lib.js, cli/lib/cert.js, cli/lib/configure.js, cli/lib/deploy-auth.js, cli/lib/gateway.js, cli/lib/init.js, cli/lib/key-gen.js, cli/lib/private.js, cli/lib/reload-cluster.js, cli/lib/rotate-key.js, cli/lib/start-agent.js, cli/lib/token.js, cli/lib/upgrade-edgeauth.js, cli/lib/upgrade-kvm.js, cli/lib/verify.js, cli/package.js, forever.js, lib/plugins.js, lib/server.js
- Replace console calls with centralized function writeConsoleLog.
- Pass writeConsoleLog to config because config doesn't having microgateway-core as a dependency to directly import writeConsoleLog
=> Adding centralized console logging

config/default.yaml
Add stack_trace flag to logging in yaml config.
If flag is set to true error stack will be printed in log file.
=> for306 138722809 Add stack_trace flag to logging

cli/cmd.js, cli/lib/configure.js, cli/lib/key-gen.js
Problem:
The `edgemicro genkeys` command does not allow a user to enter `-t` or `--token`.  It only allows username and password, which is acceptable as long as your Apigee organization does not have SSO enabled.  Once you enable SSO, then you must use JWT token for all command line tools.  
Solution:
This pull request updates the `edgemicro genkeys` command to allow a user to enter `-t` or `--token`.  
Please review and test this pull request.
=> feature: edgemicro genkeys now supports SAML enabled orgs

cli/lib/gateway.js, cli/lib/reload-cluster.js
Reload will not shut down old workers before starting new ones
Start a new worker, then stop an old worker. Wait till the worker exits gracefully or till a configurable timeout. If the worker did not exit gracefully, kill it.
Only then, start with the next worker
If already reloading, ignore new reloads
=> Fix bug 145023519 and update the reload cluster logic

kubernetes/docker/edgemicro/Dockerfile, kubernetes/docker/edgemicro/Dockerfile.beta, kubernetes/docker/edgemicro/clean.sh, kubernetes/docker/edgemicro/entrypoint.sh, kubernetes/docker/edgemicro/install-beta.sh, kubernetes/docker/edgemicro/installedgemicro.sh, kubernetes/docker/edgemicro/installnode.sh
Node alpine image contains busybox and may cause conflicts.
Moving to debian:buster-slim based node image
=> Update docker image to remove alpine

cli/lib/upgrade-kvm.js
Read entries in kvm 'microgateway'.
For each of below entries call 'Update an entry in an environment-scoped KVM' if already present and
call 'Create an entry in an environment-scoped KVM' if not present.
Private_key_kid
Public_key1
Public_key1_kid
Make all 3 calls in parallel and print success message after all are finished.
Show error message if any of the calls fails.
=> 151673570 correct upgradekvm command

cli/lib/gateway.js
Set below configs in yaml to configure admin port:
metrics:
port: 2000
Set below config if rollover of all proxy values is needed when atleast one is reached to negative or max numeric value.
metrics:
rollover_all: true
=> Make admin server port configurable

cli/cmd-private.js, cli/cmd.js, cli/lib/rotate-key.js, cli/lib/upgrade-kvm.js
Consume endpoint '/upgradeKvm' to upgrade kvm.
Consume endpoint '/rotateKey' to rotate key.
Remove redundant code.
Add key and secret keys for authorization of upgradekvm and rotatekey cli calls.
upgradekvm cmd cli params :
-o = org
-e = env
-k = key
-s = secret
-p = proxyuri
rotatekey command cli params:
-o = org
-e = env
-k = key
-s = secret
-i = kid (optional)
-r = rotatekeyuri
=> Use new endpoint for upgrade kvm and rotate key

lib/agent-config.js
Make yaml config values configurable through environment variables by adding
env variable inside tags '&lt;E&gt;' and '&lt;/E&gt;'.
Replace all the values in the config if env variable is available.
A sample config could be:
targets:
&ndash;  ssl:
client:
key: &lt;E&gt;TARGETS_SSL_CLIENT_KEY&lt;/E&gt;
cert: &lt;E&gt;TARGETS_SSL_CLIENT_CERT&lt;/E&gt;
passphrase: &lt;E&gt;TARGETS_SSL_CLIENT_PASSPHRASE&lt;/E&gt;
rejectUnauthorized: true
=> 156560067 merge env values in config.

kubernetes/docker/edgemicro/entrypoint.sh
Without this minor change we were unable to start the image when using the "EDGEMICRO_CONFIG" env variable.
=> Quote EDGEMICRO_CONFIG to properly decode it's contents

package.json
Remove heapdump dependency from project.
When running emg in heapdump mode manually install with command 'npm i heapdump -D'
=> Remove heapdump dependency

cli/cmd-private.js, cli/cmd.js, cli/lib/rotate-key.js, cli/lib/upgrade-kvm.js
Removed below options for upgradeKvm and rotateKey commands
upgradeKvm :
-t = OAuth token to use with management API
-v = virtual host of the proxy
rotateKey :
-P = previous key identifier
Private commands
upgradeKvm :
-t = OAuth token to use with management API
-v = virtual host of the proxy
rotateKey :
-t = OAuth token to use with management API
=> Remove unused options.

cli/lib/gateway.js
Pass org and env in options to config.get to make avialable for generating redis keys
=> 168681746 correct reload command to work with redis cache

cli/lib/gateway.js, lib/agent-config.js
Add key and secret from the cli options in the args object which is passed to the agent-config
Pass key and secret from the agent-config to all workers and plugins
=>  169810710 Handle caching of key and secret correctly

cli/lib/gateway.js, lib/plugins.js
Remove analytics plugin from default plugins list based on below config param in config.yaml file
edgemicro:
enableAnalytics: true/false
If enableAnalytics param is not defined or if metrics plugin is enabled, then analytics plugin exists in the default plugins list.
Include metrics option in configOptions
Add 'analytics' plugin to default plugins list, if 'metrics' plugin is enabled.
=> 170708621 new config for analytics plugin

cli/cmd.js, cli/lib/gateway.js, lib/agent-config.js
Added condition that if key and secret are stored in environment variables,
these values will be directly fetched at worker level thus avoiding values to get displayed in the node child process
Else if passed in command line arguments, it will get displayed in the node process
=> 178423436 Handle display of key,secret in node processes correctly

kubernetes/docker/edgemicro/entrypoint.sh
Optimized code for docker to stop logging into edgemicro.log file by passing a new variable to docker run “LOG_CONSOLE_OUTPUT_TO_FILE”
If this variable is set to “false” OR "False" OR "FALSE", it will not log anything in edgemicro.log file else will log into it.
Defaults to false (Will log to edgemicro.log by default)
=> 183990345 Fix logging to console issue in docker

.travis.yml, cli/edgemicro, package.json
Starting with release 3.2.2, NodeJS 8 will no longer be supported.
https://docs.apigee.com/release/notes/edge-microgateway-release-notes-0
Edge Microgateway supports NodeJS versions 10, 12, and 14.
=> 188492065 Remove support for NodeJS ver 8

kubernetes/docker/edgemicro/Dockerfile
Optimised the dockerfile to build the docker image with 12.22v of node-buster-slim, which will have upgraded NodeJS version@12.22
=> 191352643 Fix NodeJS vulnerability in docker

kubernetes/docker/edgemicro/entrypoint.sh
Optimized code to correctly execute edgemicro in a process so that it can trap SIGUSR1 and SIGTERM signals
for correctly stopping edgemicro gateway and thus cleaning up the .sock and .pid files
=> 148062415 Fix edgemicro stop issue in docker using docker stop

npm-shrinkwrap.json, package.json
- Removed support for NodeJS 10 & 12
- Updated versions of several vulnerable dependencies to enhance security.
- Starting with release 3.3.2 EMG supports NodeJS versions 14, 16, 18 and 20.
=> 274443329 Update dependencies: jsrsasign, xml2js
